name: unolist
description: "A simple offline todo list app with Flutter and Isar."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  file_picker: ^10.1.9
  collection: ^1.18.0
  url_launcher: ^6.2.5

  # Dependências adicionadas
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Dependências de desenvolvimento adicionadas
  build_runner: ^2.4.8
  isar_generator: ^3.1.0

flutter:
  uses-material-design: true
